### ISSUE TITLE
coderef behaves differently from Keyword::Simple

### ISSUE THREAD

**Issue by iynehz** [dk/Keyword-Pluggable#2]
It's good to see this library as a fork of Keyword::Simple as I am interested in using keyword in an expression rather than just at the head of a statement. But I see this library would always prepend to rest of the souce, while Keyword::Simple actually allows one to change rest of the source. For example, below demo code of Keyword::Simple would just print "foo", but how can you do the same thing with Keyword::Pluggable?

```perl
use 5.014;
use warnings;

package Foo {
    use Keyword::Simple;

    sub import {
        Keyword::Simple::define 'foo', sub {
            my ($ref) = @_;
            $$ref = q{say "foo"};
        };
    }
};

BEGIN { Foo->import; }

foo(1);
say "bar";
```

**Comment by dk** [comment]
Hi

Thanks for the feedback.
That functionality indeed first was inherited from Keyword::Simple, until in the process of simplification it was somehow phased away.
But now I'm committing it back because it wasn't intended to get rid of it.
I think the latest commit changed it, please test

/dk

**Comment by iynehz** [comment]
@dk Thanks for the quick response. But which commit? As I see it last commit as 16 days ago.

**Comment by dk** [comment]
ah, forgot git push. Pls try again
